"""agrega alert_threshold a sensor y tabla alert

Revision ID: 8dbcc7f7df0b
Revises: fdce3a329c57
Create Date: 2026-08-15 19:20:42.185627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbcc7f7df0b'
down_revision: Union[str, Sequence[str], None] = 'fdce3a329c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('reading_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['reading.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_created_at'), 'alert', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_id'), 'alert', ['id'], unique=False)
    op.create_index(op.f('ix_alert_sensor_id'), 'alert', ['sensor_id'], unique=False)
    op.add_column('sensor', sa.Column('alert_threshold', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'alert_threshold')
    op.drop_index(op.f('ix_alert_sensor_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_id'), table_name='alert')
    op.drop_index(op.f('ix_alert_created_at'), table_name='alert')
    op.drop_table('alert')
    # ### end Alembic commands ###
