"""esquema inicial: sensors y readings

Revision ID: fdce3a329c57
Revises: 
Create Date: 2026-08-07 00:19:13.217612

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fdce3a329c57'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_id'), 'sensor', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_name'), 'sensor', ['name'], unique=False)
    op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_created_at'), 'reading', ['created_at'], unique=False)
    op.create_index(op.f('ix_reading_id'), 'reading', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_id'), table_name='reading')
    op.drop_index(op.f('ix_reading_created_at'), table_name='reading')
    op.drop_table('reading')
    op.drop_index(op.f('ix_sensor_name'), table_name='sensor')
    op.drop_index(op.f('ix_sensor_id'), table_name='sensor')
    op.drop_table('sensor')
    # ### end Alembic commands ###
